spring.application.name=Payment

# ===============================
# --- EUREKA DISCOVERY ---
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:7010/eureka}
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true



# ===============================
# --- STRIPE CONFIG ---
# ===============================

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.success.url=http://127.0.0.1:3000/payment/success
stripe.cancel.url=http://127.0.0.1:3000/payment/cancel