spring.application.name=Cart
server.port=7041

# ===============================
#EUREKA
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:7010/eureka}
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true